services:
  pdf-chatbot:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads
      - ./temp_pdfs:/app/temp_pdfs
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - TEMP_PATH=/app/temp_pdfs
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.00.0.0/00
