version: '3.8'

services:
  pdf-chatbot:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
